### ISSUE TITLE
Take non-iRODS resources into acccout ?

### ISSUE THREAD

**Issue by sviscapi** [raphael-ritz/eudat.accounting.client#9]
Dear @raphael-ritz ,

We have ~24TB of data registered in the HERBADROP-B2SAFE project:

https://dp.eudat.eu/providers/CINES/herbadrop-b2safe

Part of this data has also been archived for long term preservation in another part of our computing system (not related to iRODS AFAIK), but is not accounted for (yet).

Would it be possible to take non-iRODS resources into account with the EUDAT client ?

Best regards,

Samuel, from CINES

**Comment by raphael-ritz** [comment]
Hi Samuel,

of course you can file accounting records for non-iRODS-based resources.

There are two ways in which you can do that:

1. low-level as described here: 
https://github.com/EUDAT-DPMT/eudat.accounting.server#adding-records

2. using the command line client as described here: 
https://github.com/EUDAT-DPMT/eudat.accounting.client#addrecord

Note that in both cases you will need to specify the uid of the
"Registered Storage Resoure" in DPMT and you need credentials
for CINES on the accounting service. Do you have those?
Otherwise I can provide them for you.

Hope that helps,

     Raphael

**Comment by sviscapi** [comment]
Hi Raphael,

Thank you for your quick reply ! I'll give addrecord a new try ASAP.

Cheers, Samuel
